const map = {
    0: {
        // Bugs
        1: {
            region: 'Wise Region',
            capital: 'New New York',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        2: {
            region: 'Kruger System',
            capital: 'Liberty City',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        3: {
            region: 'Ross System',
            capital: 'Tiberia',
            percentage: 0,
            points_max: 0,
            points: 0,
        },

        4: {
            region: 'Struve Region',
            capital: "Northman's Creek",
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        5: {
            region: 'Xi Tauri Region',
            capital: 'New Haven',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        6: {
            region: 'Cancri System',
            capital: 'Freedom Fortress',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        7: {
            region: 'Higgs Region',
            capital: "Martyr's Bay",
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        8: {
            region: 'Hawking Region',
            capital: 'Segma Prime',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        9: {
            region: 'Rigel System',
            capital: 'Freedom Peak',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        10: {
            region: 'Aurigae Region',
            capital: 'Final Frontier',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        11: {
            //Kepler System, Bugs Homeworld
            region: 'Kepler System',
            capital: 'Kepler Prime',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
    },
    1: {
        // Cyborgs
        1: {
            region: 'Sirius Region',
            capital: 'Stockholm City',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        2: {
            region: 'Polaris Region',
            capital: 'Thunder Head',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        3: {
            region: 'Pictor Sector',
            capital: 'New Moscow',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        4: {
            region: 'Sagan Region',
            capital: 'Highwind',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        5: {
            region: 'Horolium System',
            capital: 'Providence',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        6: {
            region: 'Gellert Region',
            capital: 'Gellert City',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        7: {
            region: 'Lacaille Region',
            capital: 'Bahia Democracia',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        8: {
            region: 'Indi System',
            capital: 'Winter Hold',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        9: {
            region: 'Ceti System',
            capital: 'Doral Creek',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        10: {
            region: 'Cygni Region',
            capital: 'New Berlin',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        11: {
            // //Cyberstan Region, Cyborgs Homeworld
            region: 'Cyberstan Region',
            capital: 'Cyberstan',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
    },
    2: {
        // The Illuminate
        1: {
            region: 'Centaury Region',
            capital: 'New Hanover',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        2: {
            region: 'Barnard Region',
            capital: 'Iron Tower',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        3: {
            region: 'Procyon Region',
            capital: 'White Landing',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        4: {
            region: 'Castor System',
            capital: 'Justice Bay',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        5: {
            region: 'Orionis Region',
            capital: 'New Alexandria',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        6: {
            region: 'Prometheus System',
            capital: 'Ribatishiti',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        7: {
            region: 'Cassiopaiae Region',
            capital: 'Dal Rage',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        8: {
            region: 'Ursa Region',
            capital: 'Ultima',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        9: {
            region: 'Canes Region',
            capital: 'Jiyu Toshi',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        10: {
            region: 'Arcturus Region',
            capital: 'Hawk Nest',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        11: {
            // //Squ'bai System, The Illuminate Homeworld
            region: "Squ'bai System",
            capital: "Squ'bai Shrine",
            percentage: 0,
            points_max: 0,
            points: 0,
        },
    },
    3: {
        0: {
            region: 'Sol System',
            capital: 'Super Earth',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
        1: {
            region: 'Sol System',
            capital: 'Super Earth',
            percentage: 0,
            points_max: 0,
            points: 0,
        },
    },
};

export default map;
